#include "DesktopEntryWriter.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>
#include <QStandardPaths>
#include <QTextStream>

#include <algorithm>
#include <stdexcept>

namespace {
constexpr const char *generatedComment = "Generated by StartupApp";

QString applicationsDirectory()
{
    return QStandardPaths::writableLocation(QStandardPaths::ApplicationsLocation);
}

QString autostartDirectory()
{
    return QDir::homePath() + "/.config/autostart";
}

QString iconsDirectory()
{
    return QDir::homePath() + "/.local/share/icons";
}

QString valueForDesktopKey(const QString &text, const QString &key)
{
    const QString prefix = key + "=";
    const QStringList lines = text.split('\n');
    for (const QString &line : lines) {
        if (line.startsWith(prefix)) {
            return line.mid(prefix.length()).trimmed();
        }
    }
    return {};
}

bool isInstalledStartupAppIcon(const QString &appId, const QString &iconPath)
{
    if (iconPath.trimmed().isEmpty()) {
        return false;
    }

    const QFileInfo iconInfo(iconPath);
    const QFileInfo iconsDirInfo(iconsDirectory());
    return iconInfo.exists() &&
           iconInfo.absolutePath() == iconsDirInfo.absoluteFilePath() &&
           iconInfo.completeBaseName() == appId;
}
}

QString DesktopEntryWriter::validate(const DesktopAppConfig &config)
{
    if (config.appName.trimmed().isEmpty()) {
        return "应用名不能为空。";
    }

    if (config.command.trimmed().isEmpty()) {
        return "运行命令或脚本不能为空。";
    }

    if (!config.iconPath.trimmed().isEmpty() && !QFileInfo::exists(config.iconPath)) {
        return "选择的图片文件不存在。";
    }

    return {};
}

DesktopAppResult DesktopEntryWriter::write(const DesktopAppConfig &config)
{
    const QString validationError = validate(config);
    if (!validationError.isEmpty()) {
        throw std::runtime_error(validationError.toStdString());
    }

    DesktopAppResult result;
    result.appId = appIdFromName(config.appName);

    const QString applicationsDir = applicationsDirectory();
    const QString autostartDir = autostartDirectory();

    ensureDirectory(applicationsDir);
    ensureDirectory(autostartDir);

    result.installedIconPath = installIcon(result.appId, config.iconPath.trimmed());
    const QString entryText = desktopEntryText(config, result.installedIconPath);

    result.desktopFilePath = applicationsDir + "/" + result.appId + ".desktop";
    QFile desktopFile(result.desktopFilePath);
    if (!desktopFile.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        throw std::runtime_error(("无法写入应用文件：" + desktopFile.errorString()).toStdString());
    }
    desktopFile.write(entryText.toUtf8());
    desktopFile.close();
    desktopFile.setPermissions(QFile::ReadOwner | QFile::WriteOwner | QFile::ExeOwner |
                               QFile::ReadGroup | QFile::ExeGroup |
                               QFile::ReadOther | QFile::ExeOther);

    result.autostartFilePath = autostartDir + "/" + result.appId + ".desktop";
    if (config.autostart) {
        QFile autostartFile(result.autostartFilePath);
        if (!autostartFile.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
            throw std::runtime_error(("无法写入自启动文件：" + autostartFile.errorString()).toStdString());
        }
        autostartFile.write(entryText.toUtf8());
        autostartFile.close();
        autostartFile.setPermissions(QFile::ReadOwner | QFile::WriteOwner | QFile::ExeOwner |
                                     QFile::ReadGroup | QFile::ExeGroup |
                                     QFile::ReadOther | QFile::ExeOther);
    } else if (QFileInfo::exists(result.autostartFilePath)) {
        QFile::remove(result.autostartFilePath);
    }

    return result;
}

QVector<DesktopAppInfo> DesktopEntryWriter::generatedApplications()
{
    QVector<DesktopAppInfo> apps;
    const QDir applicationsDir(applicationsDirectory());
    const QFileInfoList desktopFiles =
        applicationsDir.entryInfoList({"*.desktop"}, QDir::Files, QDir::Name);

    for (const QFileInfo &desktopInfo : desktopFiles) {
        QFile file(desktopInfo.absoluteFilePath());
        if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
            continue;
        }

        const QString text = QString::fromUtf8(file.readAll());
        if (valueForDesktopKey(text, "Comment") != QString::fromUtf8(generatedComment)) {
            continue;
        }

        DesktopAppInfo app;
        app.appId = desktopInfo.completeBaseName();
        app.appName = valueForDesktopKey(text, "Name");
        if (app.appName.isEmpty()) {
            app.appName = app.appId;
        }
        app.desktopFilePath = desktopInfo.absoluteFilePath();
        app.autostartFilePath = autostartDirectory() + "/" + app.appId + ".desktop";
        app.installedIconPath = valueForDesktopKey(text, "Icon");
        apps.push_back(app);
    }

    std::sort(apps.begin(), apps.end(), [](const DesktopAppInfo &left, const DesktopAppInfo &right) {
        return QString::localeAwareCompare(left.appName, right.appName) < 0;
    });

    return apps;
}

DesktopAppInfo DesktopEntryWriter::findGeneratedApplication(const QString &appId)
{
    const QVector<DesktopAppInfo> apps = generatedApplications();
    for (const DesktopAppInfo &app : apps) {
        if (app.appId == appId) {
            return app;
        }
    }

    return {};
}

void DesktopEntryWriter::removeGeneratedApplication(const QString &appId)
{
    const DesktopAppInfo app = findGeneratedApplication(appId);
    if (app.appId.isEmpty()) {
        throw std::runtime_error("找不到这个由 StartupApp 生成的应用。");
    }

    QStringList errors;
    if (QFileInfo::exists(app.desktopFilePath) && !QFile::remove(app.desktopFilePath)) {
        errors << "无法删除应用入口：" + app.desktopFilePath;
    }

    if (QFileInfo::exists(app.autostartFilePath) && !QFile::remove(app.autostartFilePath)) {
        errors << "无法删除自启动入口：" + app.autostartFilePath;
    }

    if (isInstalledStartupAppIcon(app.appId, app.installedIconPath) &&
        !QFile::remove(app.installedIconPath)) {
        errors << "无法删除应用图片：" + app.installedIconPath;
    }

    if (!errors.isEmpty()) {
        throw std::runtime_error(errors.join('\n').toStdString());
    }
}

QString DesktopEntryWriter::appIdFromName(const QString &name)
{
    QString id = name.trimmed().toLower();
    id.replace(QRegularExpression("[^a-z0-9._-]+"), "-");
    id.replace(QRegularExpression("-+"), "-");
    id = id.trimmed();
    while (id.startsWith('-') || id.startsWith('.')) {
        id.remove(0, 1);
    }
    while (id.endsWith('-') || id.endsWith('.')) {
        id.chop(1);
    }

    if (id.isEmpty()) {
        id = "startup-app";
    }

    return id;
}

QString DesktopEntryWriter::desktopEntryText(const DesktopAppConfig &config, const QString &iconPath)
{
    const QString terminalCommand = config.command.trimmed() + "; exec bash";

    QString text;
    QTextStream stream(&text);
    stream << "[Desktop Entry]\n";
    stream << "Type=Application\n";
    stream << "Name=" << config.appName.trimmed() << "\n";
    stream << "Comment=Generated by StartupApp\n";
    stream << "Exec=gnome-terminal --title "
           << desktopArgumentQuote(config.appName.trimmed())
           << " -- bash -ic "
           << desktopArgumentQuote(terminalCommand)
           << "\n";
    if (!iconPath.isEmpty()) {
        stream << "Icon=" << iconPath << "\n";
    }
    stream << "Terminal=false\n";
    stream << "Categories=Utility;\n";
    stream << "StartupNotify=false\n";
    return text;
}

QString DesktopEntryWriter::desktopArgumentQuote(const QString &value)
{
    QString quoted = value;
    quoted.replace("\\", "\\\\");
    quoted.replace("\"", "\\\"");
    quoted.replace("$", "\\$");
    quoted.replace("`", "\\`");
    return "\"" + quoted + "\"";
}

void DesktopEntryWriter::ensureDirectory(const QString &path)
{
    QDir dir(path);
    if (!dir.exists() && !dir.mkpath(".")) {
        throw std::runtime_error(("无法创建目录：" + path).toStdString());
    }
}

QString DesktopEntryWriter::installIcon(const QString &appId, const QString &sourcePath)
{
    if (sourcePath.isEmpty()) {
        return {};
    }

    QFileInfo sourceInfo(sourcePath);
    QString suffix = sourceInfo.suffix().toLower();
    if (suffix.isEmpty()) {
        suffix = "png";
    }

    const QString iconsDir = iconsDirectory();
    ensureDirectory(iconsDir);

    const QString destination = iconsDir + "/" + appId + "." + suffix;
    if (QFileInfo(sourcePath).absoluteFilePath() != QFileInfo(destination).absoluteFilePath()) {
        QFile::remove(destination);
        if (!QFile::copy(sourcePath, destination)) {
            throw std::runtime_error(("无法复制图片到：" + destination).toStdString());
        }
    }

    return destination;
}
