#include "DesktopEntryWriter.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>
#include <QStandardPaths>
#include <QTextStream>

#include <stdexcept>

QString DesktopEntryWriter::validate(const DesktopAppConfig &config)
{
    if (config.appName.trimmed().isEmpty()) {
        return "应用名不能为空。";
    }

    if (config.command.trimmed().isEmpty()) {
        return "运行命令或脚本不能为空。";
    }

    if (!config.iconPath.trimmed().isEmpty() && !QFileInfo::exists(config.iconPath)) {
        return "选择的图片文件不存在。";
    }

    return {};
}

DesktopAppResult DesktopEntryWriter::write(const DesktopAppConfig &config)
{
    const QString validationError = validate(config);
    if (!validationError.isEmpty()) {
        throw std::runtime_error(validationError.toStdString());
    }

    DesktopAppResult result;
    result.appId = appIdFromName(config.appName);

    const QString applicationsDir =
        QStandardPaths::writableLocation(QStandardPaths::ApplicationsLocation);
    const QString autostartDir =
        QDir::homePath() + "/.config/autostart";

    ensureDirectory(applicationsDir);
    ensureDirectory(autostartDir);

    result.installedIconPath = installIcon(result.appId, config.iconPath.trimmed());
    const QString entryText = desktopEntryText(config, result.installedIconPath);

    result.desktopFilePath = applicationsDir + "/" + result.appId + ".desktop";
    QFile desktopFile(result.desktopFilePath);
    if (!desktopFile.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        throw std::runtime_error(("无法写入应用文件：" + desktopFile.errorString()).toStdString());
    }
    desktopFile.write(entryText.toUtf8());
    desktopFile.close();
    desktopFile.setPermissions(QFile::ReadOwner | QFile::WriteOwner | QFile::ExeOwner |
                               QFile::ReadGroup | QFile::ExeGroup |
                               QFile::ReadOther | QFile::ExeOther);

    result.autostartFilePath = autostartDir + "/" + result.appId + ".desktop";
    if (config.autostart) {
        QFile autostartFile(result.autostartFilePath);
        if (!autostartFile.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
            throw std::runtime_error(("无法写入自启动文件：" + autostartFile.errorString()).toStdString());
        }
        autostartFile.write(entryText.toUtf8());
        autostartFile.close();
        autostartFile.setPermissions(QFile::ReadOwner | QFile::WriteOwner | QFile::ExeOwner |
                                     QFile::ReadGroup | QFile::ExeGroup |
                                     QFile::ReadOther | QFile::ExeOther);
    } else if (QFileInfo::exists(result.autostartFilePath)) {
        QFile::remove(result.autostartFilePath);
    }

    return result;
}

QString DesktopEntryWriter::appIdFromName(const QString &name)
{
    QString id = name.trimmed().toLower();
    id.replace(QRegularExpression("[^a-z0-9._-]+"), "-");
    id.replace(QRegularExpression("-+"), "-");
    id = id.trimmed();
    while (id.startsWith('-') || id.startsWith('.')) {
        id.remove(0, 1);
    }
    while (id.endsWith('-') || id.endsWith('.')) {
        id.chop(1);
    }

    if (id.isEmpty()) {
        id = "startup-app";
    }

    return id;
}

QString DesktopEntryWriter::desktopEntryText(const DesktopAppConfig &config, const QString &iconPath)
{
    const QString terminalCommand = config.command.trimmed() + "; exec bash";

    QString text;
    QTextStream stream(&text);
    stream << "[Desktop Entry]\n";
    stream << "Type=Application\n";
    stream << "Name=" << config.appName.trimmed() << "\n";
    stream << "Comment=Generated by StartupApp\n";
    stream << "Exec=gnome-terminal --title "
           << desktopArgumentQuote(config.appName.trimmed())
           << " -- bash -ic "
           << desktopArgumentQuote(terminalCommand)
           << "\n";
    if (!iconPath.isEmpty()) {
        stream << "Icon=" << iconPath << "\n";
    }
    stream << "Terminal=false\n";
    stream << "Categories=Utility;\n";
    stream << "StartupNotify=false\n";
    return text;
}

QString DesktopEntryWriter::desktopArgumentQuote(const QString &value)
{
    QString quoted = value;
    quoted.replace("\\", "\\\\");
    quoted.replace("\"", "\\\"");
    quoted.replace("$", "\\$");
    quoted.replace("`", "\\`");
    return "\"" + quoted + "\"";
}

void DesktopEntryWriter::ensureDirectory(const QString &path)
{
    QDir dir(path);
    if (!dir.exists() && !dir.mkpath(".")) {
        throw std::runtime_error(("无法创建目录：" + path).toStdString());
    }
}

QString DesktopEntryWriter::installIcon(const QString &appId, const QString &sourcePath)
{
    if (sourcePath.isEmpty()) {
        return {};
    }

    QFileInfo sourceInfo(sourcePath);
    QString suffix = sourceInfo.suffix().toLower();
    if (suffix.isEmpty()) {
        suffix = "png";
    }

    const QString iconsDir = QDir::homePath() + "/.local/share/icons";
    ensureDirectory(iconsDir);

    const QString destination = iconsDir + "/" + appId + "." + suffix;
    if (QFileInfo(sourcePath).absoluteFilePath() != QFileInfo(destination).absoluteFilePath()) {
        QFile::remove(destination);
        if (!QFile::copy(sourcePath, destination)) {
            throw std::runtime_error(("无法复制图片到：" + destination).toStdString());
        }
    }

    return destination;
}
